# from __future__ import annotations

# import os
# import smtplib
# from email.mime.text import MIMEText
# from email.mime.multipart import MIMEMultipart
# from typing import Any, Dict

# from app.ta.trade_engine_tv import TradePlan


# # =========================
# # HTML wrapper (שלך)
# # =========================
# def build_email_html(title: str, html_body: str) -> str:
#     return f"""\
# <!doctype html>
# <html>
#   <head>
#     <meta charset="utf-8" />
#     <title>{title}</title>
#   </head>
#   <body style="font-family: Arial, sans-serif; line-height: 1.5;">
#     <h2>{title}</h2>
#     {html_body}
#     <hr/>
#     <div style="font-size:12px; color:#666;">
#       Generated by stocks-alerts
#     </div>
#   </body>
# </html>
# """


# # =========================
# # Build email content
# # =========================
# def build_email(plan: TradePlan, tv: Dict[str, Any]) -> tuple[str, str]:
#     ticker = tv.get("ticker", "UNKNOWN")
#     signal = tv.get("signal", "SIGNAL")
#     interval = tv.get("interval", "")

#     title = f"{ticker} – {signal} ({interval})"

#     rows = [
#         ("Entry", plan.entry),
#         ("Stop", plan.stop),
#         ("TP1", plan.tp1),
#         ("TP2", plan.tp2),
#         ("RR1", plan.rr1),
#         ("RR2", plan.rr2),
#         ("Shares", plan.position_size_shares),
#         ("Position $", plan.position_notional),
#     ]

#     html_rows = "".join(
#         f"<tr><td><b>{k}</b></td><td>{v}</td></tr>" for k, v in rows if v is not None
#     )

#     notes_html = ""
#     if plan.notes:
#         notes_html = (
#             "<h3>Notes</h3><ul>"
#             + "".join(f"<li>{n}</li>" for n in plan.notes)
#             + "</ul>"
#         )

#     html_body = f"""
# <table border="1" cellpadding="6" cellspacing="0">
#   {html_rows}
# </table>

# {notes_html}

# <h3>Raw TradingView payload</h3>
# <pre style="background:#f5f5f5; padding:10px; font-size:12px;">
# {tv}
# </pre>
# """

#     return title, build_email_html(title, html_body)


# # =========================
# # Send email (SMTP)
# # =========================
# def send_email(*, to_email: str, subject: str, html: str) -> None:
#     smtp_host = os.getenv("SMTP_HOST")
#     smtp_port = int(os.getenv("SMTP_PORT", "587"))
#     smtp_user = os.getenv("SMTP_USER")
#     smtp_password = os.getenv("SMTP_PASSWORD")
#     from_email = os.getenv("FROM_EMAIL", smtp_user)

#     if not all([smtp_host, smtp_user, smtp_password, from_email]):
#         raise RuntimeError("Missing SMTP configuration in environment variables")

#     msg = MIMEMultipart("alternative")
#     msg["Subject"] = subject
#     msg["From"] = from_email
#     msg["To"] = to_email

#     msg.attach(MIMEText(html, "html"))

#     with smtplib.SMTP(smtp_host, smtp_port) as server:
#         server.starttls()
#         server.login(smtp_user, smtp_password)
#         server.sendmail(from_email, [to_email], msg.as_string())


# from __future__ import annotations

# import smtplib
# from email.mime.text import MIMEText

# from app.core.settings import EMAIL_HOST, EMAIL_PORT, EMAIL_USER, EMAIL_PASS, EMAIL_TO


# def build_email_html(title: str, html_body: str) -> str:
#     return f"""\
# <!doctype html>
# <html>
#   <head>
#     <meta charset="utf-8" />
#     <title>{title}</title>
#   </head>
#   <body style="font-family: Arial, sans-serif; line-height: 1.5;">
#     <h2>{title}</h2>
#     {html_body}
#     <hr/>
#     <div style="font-size:12px; color:#666;">
#       Generated by stocks-alerts
#     </div>
#   </body>
# </html>
# """


# def send_email(*, subject: str, html: str) -> None:
#     if not EMAIL_TO:
#         raise RuntimeError("EMAIL_TO is missing in env")
#     if not EMAIL_USER or not EMAIL_PASS:
#         raise RuntimeError("EMAIL_USER / EMAIL_PASS missing in env")

#     msg = MIMEText(html, "html", "utf-8")
#     msg["Subject"] = subject
#     msg["From"] = EMAIL_USER
#     msg["To"] = EMAIL_TO

#     with smtplib.SMTP(EMAIL_HOST, EMAIL_PORT) as server:
#         server.starttls()
#         server.login(EMAIL_USER, EMAIL_PASS)
#         server.sendmail(EMAIL_USER, [EMAIL_TO], msg.as_string())


# from __future__ import annotations

# import os
# import smtplib
# from datetime import datetime
# from typing import Any, Dict, List, Tuple

# from email.mime.multipart import MIMEMultipart
# from email.mime.text import MIMEText

# import yfinance as yf

# from app.ta.ta_engine import confluence_score, trade_plan, checklist_technical
# from app.ta.fundamentals_us import fetch_fundamentals_us
# from app.services.ai_summarizer import summarize_fundamentals_he

# from app.services.news_provider import get_company_news
# from app.services.ai_news_summarizer import summarize_news_he


# SMTP_HOST = os.getenv("SMTP_HOST", "")
# SMTP_PORT = int(os.getenv("SMTP_PORT", "465"))
# SMTP_USER = os.getenv("SMTP_USER", "")
# SMTP_PASS = os.getenv("SMTP_PASS", "")
# ALERT_TO_EMAIL = os.getenv("ALERT_TO_EMAIL", "")


# def build_email_html(title: str, html_body: str) -> str:
#     print("sent email start")
#     return f"""\
# <!doctype html>
# <html>
#   <head>
#     <meta charset="utf-8" />
#     <title>{title}</title>
#   </head>
#   <body style="font-family: Arial, sans-serif; line-height: 1.5; direction: rtl;">
#     <h2>{title}</h2>
#     {html_body}
#     <hr/>
#     <div style="font-size:12px; color:#666;">
#       Generated by stocks-alerts
#     </div>
#   </body>
# </html>
# """


# def build_email(
#     ticker: str,
#     interval: str,
#     signal: str,
#     close: float,
#     *,
#     tv_payload: Dict[str, Any] | None = None,
# ) -> Tuple[str, str]:
#     tv_payload = tv_payload or {}

#     # ========= 1) Price data (Daily MVP) =========
#     df = yf.download(ticker, period="1y", interval="1d", auto_adjust=False, progress=False)

#     if hasattr(df.columns, "levels"):
#         df.columns = [c[0] if isinstance(c, tuple) else c for c in df.columns]

#     df = df.rename(columns={
#         "Open": "open",
#         "High": "high",
#         "Low": "low",
#         "Close": "close",
#         "Volume": "volume",
#     })
#     df = df[["open", "high", "low", "close", "volume"]].dropna()

#     # ========= 2) Technical =========
#     tech = confluence_score(df)
#     plan = trade_plan(df, tech, rr_min=2.0)
#     chk = checklist_technical(df, tech)

#     # ========= 3) Fundamentals + AI =========
#     fundamentals = {"checks": {}, "metrics": {}, "ai_input": ""}
#     try:
#         fundamentals = fetch_fundamentals_us(ticker)
#     except Exception:
#         fundamentals = {"checks": {}, "metrics": {}, "ai_input": ""}

#     checks = fundamentals.get("checks", {}) or {}
#     metrics = fundamentals.get("metrics", {}) or {}

#     ai_fund = ""
#     try:
#         ai_fund = summarize_fundamentals_he(fundamentals.get("ai_input", "") or "")
#     except Exception:
#         ai_fund = ""

#     # ========= 4) News + AI =========
#     news: List[Dict[str, Any]] = []
#     try:
#         news = get_company_news(ticker, limit=6)
#     except Exception:
#         news = []

#     ai_news = ""
#     try:
#         ai_news = summarize_news_he(
#             ticker=ticker,
#             signal=signal,
#             tv_payload=tv_payload,
#             news=news,
#         )
#     except Exception:
#         ai_news = ""

#     # ========= helpers =========
#     def esc(x) -> str:
#         if x is None:
#             return ""
#         s = str(x)
#         return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

#     def pct(x):
#         if x is None:
#             return "—"
#         try:
#             return f"{float(x):.2f}%"
#         except Exception:
#             return esc(x)

#     # ========= Subject =========
#     subject = f"📈 התראת סווינג | {ticker} | {signal} | ציון {tech.get('score', 0)}/4"

#     # Confluence reasons
#     reasons = tech.get("reasons") or []
#     tech_reasons_html = "".join(f"<li>{esc(r)}</li>" for r in reasons) or "<li>—</li>"

#     # Trade plan
#     if plan.get("ok"):
#         plan_html = f"""
#         <table style="width:100%; border-collapse: collapse;">
#           <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">אזור כניסה</td><td style="border:1px solid #eee;padding:8px">{esc(plan["entry_zone"]["low"])} – {esc(plan["entry_zone"]["high"])}</td></tr>
#           <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">סטופ לוס</td><td style="border:1px solid #eee;padding:8px"><b>{esc(plan["stop_loss"])}</b></td></tr>
#           <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">יעד 1</td><td style="border:1px solid #eee;padding:8px">{esc(plan["tp1"])} (RR {esc(plan["rr1"])})</td></tr>
#           <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">יעד 2</td><td style="border:1px solid #eee;padding:8px">{esc(plan["tp2"])} (RR {esc(plan["rr2"])})</td></tr>
#         </table>
#         """
#     else:
#         plan_html = f"<div style='padding:10px;background:#fff6f6;border:1px solid #ffd2d2;border-radius:10px'>לא נוצרה תוכנית עסקה: {esc(plan.get('reason','—'))}</div>"

#     # Fundamentals
#     if checks:
#         checks_rows = "".join(
#             f"<tr><td style='border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700'>{esc(k)}</td><td style='border:1px solid #eee;padding:8px'>{esc(v)}</td></tr>"
#             for k, v in checks.items()
#         )
#         fundamentals_html = f"""
#         <table style="width:100%; border-collapse: collapse;">
#           {checks_rows}
#         </table>
#         <div style="margin-top:8px;font-size:12px;color:#444">
#           P/E: {esc(metrics.get("pe"))} ·
#           Revenue CAGR: {pct((metrics.get("rev_cagr") or 0) * 100 if metrics.get("rev_cagr") is not None else None)} ·
#           Net Income CAGR: {pct((metrics.get("ni_cagr") or 0) * 100 if metrics.get("ni_cagr") is not None else None)} ·
#           FCF CAGR: {pct((metrics.get("fcf_cagr") or 0) * 100 if metrics.get("fcf_cagr") is not None else None)}
#         </div>
#         """
#     else:
#         fundamentals_html = "<div style='padding:10px;background:#fff6f6;border:1px solid #ffd2d2;border-radius:10px'>לא הצלחתי למשוך נתונים פונדמנטליים כרגע.</div>"

#     # News list
#     if news:
#         news_items = "".join(
#             f"<li><b>{esc(n.get('source',''))}</b> — {esc(n.get('title',''))} "
#             f"<span style='color:#666;font-size:12px'>({esc(n.get('published_at',''))})</span> "
#             f"— <a href='{esc(n.get('url',''))}'>קישור</a></li>"
#             for n in news
#         )
#     else:
#         news_items = "<li>לא נמצאו חדשות משמעותיות כרגע.</li>"

#     # AI blocks
#     ai_fund_block = ""
#     if ai_fund.strip():
#         ai_fund_block = f"<div style='background:#f6f6f6;border:1px solid #eee;border-radius:10px;padding:10px;white-space:pre-wrap'>{esc(ai_fund)}</div>"

#     ai_news_block = ""
#     if ai_news.strip():
#         ai_news_block = f"<div style='background:#f6f6f6;border:1px solid #eee;border-radius:10px;padding:10px;white-space:pre-wrap'>{esc(ai_news)}</div>"

#     # ========= Final body =========
#     body = f"""
#     <div style="background:#f5f7fb;padding:12px;border-radius:12px">
#       <div style="background:#fff;padding:12px;border-radius:12px;border:1px solid #e6e8ef">
#         <div style="font-size:18px;font-weight:800">📊 התראת סווינג – {esc(ticker)}</div>
#         <div style="color:#555;font-size:13px;margin-top:6px">
#           <b>טיימפריים:</b> {esc(interval)} · <b>סיגנל:</b> {esc(signal)} · <b>מחיר:</b> {esc(close)} ·
#           <b>UTC:</b> {esc(datetime.utcnow().isoformat(timespec="seconds"))}
#         </div>
#       </div>

#       <div style="background:#fff;padding:12px;border-radius:12px;border:1px solid #e6e8ef;margin-top:10px">
#         <div style="font-weight:800;margin-bottom:6px">🧠 Confluence</div>
#         <div><b>ציון:</b> {esc(tech.get("score"))}/4</div>
#         <ul>{tech_reasons_html}</ul>
#       </div>

#       <div style="background:#fff;padding:12px;border-radius:12px;border:1px solid #e6e8ef;margin-top:10px">
#         <div style="font-weight:800;margin-bottom:6px">🎯 Trade Plan (1% risk)</div>
#         {plan_html}
#       </div>

#       <div style="background:#fff;padding:12px;border-radius:12px;border:1px solid #e6e8ef;margin-top:10px">
#         <div style="font-weight:800;margin-bottom:6px">✅ צ’ק־ליסט</div>
#         <table style="width:100%; border-collapse: collapse;">
#           <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">נר אחרון</td><td style="border:1px solid #eee;padding:8px">{esc(chk.get("candle"))}</td></tr>
#           <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">מגמה שבועית</td><td style="border:1px solid #eee;padding:8px">{esc(chk.get("trend_week_pct"))}%</td></tr>
#           <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">מגמה חודשית</td><td style="border:1px solid #eee;padding:8px">{esc(chk.get("trend_month_pct"))}%</td></tr>
#           <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">ווליום</td><td style="border:1px solid #eee;padding:8px">{esc(chk.get("volume"))}</td></tr>
#           <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">MA20</td><td style="border:1px solid #eee;padding:8px">{esc(chk.get("ma20"))}</td></tr>
#           <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">מצב כללי</td><td style="border:1px solid #eee;padding:8px">{esc(chk.get("bull_bear"))}</td></tr>
#         </table>
#       </div>

#       <div style="background:#fff;padding:12px;border-radius:12px;border:1px solid #e6e8ef;margin-top:10px">
#         <div style="font-weight:800;margin-bottom:6px">📘 פונדמנטלי (ארה״ב)</div>
#         {fundamentals_html}
#         <div style="margin-top:10px">
#           <div style="font-weight:800;margin-bottom:6px">🤖 סיכום פונדמנטלי (AI)</div>
#           {ai_fund_block or "<div style='color:#666'>—</div>"}
#         </div>
#       </div>

#       <div style="background:#fff;padding:12px;border-radius:12px;border:1px solid #e6e8ef;margin-top:10px">
#         <div style="font-weight:800;margin-bottom:6px">📰 חדשות אחרונות (Finnhub/RSS)</div>
#         <ul>{news_items}</ul>
#         <div style="margin-top:10px">
#           <div style="font-weight:800;margin-bottom:6px">🧠 למה עכשיו? (News + AI)</div>
#           {ai_news_block or "<div style='color:#666'>—</div>"}
#         </div>
#       </div>

#       <div style="margin-top:12px;color:#777;font-size:12px">
#         ⚠️ למידע לימודי בלבד, לא ייעוץ השקעות.
#       </div>
#     </div>
#     """

#     return subject, build_email_html(subject, body)


# # def send_email(subject: str, html: str):
# #     msg = MIMEMultipart("alternative")
# #     msg["Subject"] = subject
# #     msg["From"] = SMTP_USER
# #     msg["To"] = ALERT_TO_EMAIL

# #     msg.attach(MIMEText(html, "html", "utf-8"))

# #     with smtplib.SMTP_SSL(SMTP_HOST, SMTP_PORT) as smtp:
# #         smtp.login(SMTP_USER, SMTP_PASS)
# #         smtp.send_message(msg)

# def send_email(subject: str, html: str):
#     print(f"[EMAIL] send_email called subject={subject!r}")

#     msg = MIMEMultipart("alternative")
#     msg["Subject"] = subject
#     msg["From"] = SMTP_USER
#     msg["To"] = ALERT_TO_EMAIL

#     msg.attach(MIMEText(html, "html", "utf-8"))

#     print(f"[EMAIL] SMTP={SMTP_HOST}:{SMTP_PORT} USER={SMTP_USER} TO={ALERT_TO_EMAIL}")

#     try:
#         with smtplib.SMTP_SSL(SMTP_HOST, int(SMTP_PORT)) as smtp:
#             smtp.login(SMTP_USER, SMTP_PASS)
#             smtp.send_message(msg)
#         print("[EMAIL] sent ✅")
#     except Exception as e:
#         print(f"[EMAIL] FAILED ❌ {type(e).__name__}: {e}")
#         raise


# from __future__ import annotations

# import os
# import smtplib
# from datetime import datetime
# from typing import Any, Dict, List, Tuple

# from email.mime.multipart import MIMEMultipart
# from email.mime.text import MIMEText
# import socket
# import smtplib
# import yfinance as yf

# import os
# from sendgrid import SendGridAPIClient
# from sendgrid.helpers.mail import Mail


# # הנחה שהקבצים האלו קיימים בפרויקט שלך
# from app.ta.ta_engine import confluence_score, trade_plan, checklist_technical
# from app.ta.fundamentals_us import fetch_fundamentals_us
# from app.services.ai_summarizer import summarize_fundamentals_he
# from app.services.news_provider import get_company_news
# from app.services.ai_news_summarizer import summarize_news_he


# # --- הגדרות סביבה ---
# SMTP_HOST = os.getenv("SMTP_HOST", "")
# SMTP_PORT = int(os.getenv("SMTP_PORT", "25"))
# SMTP_USER = os.getenv("SMTP_USER", "")
# SMTP_PASS = os.getenv("SMTP_PASS", "")
# ALERT_TO_EMAIL = os.getenv("ALERT_TO_EMAIL", "")


# def build_email_html(title: str, html_body: str) -> str:
#     """עוטף את תוכן המייל בתבנית HTML בסיסית"""
#     return f"""\
# <!doctype html>
# <html>
#   <head>
#     <meta charset="utf-8" />
#     <title>{title}</title>
#   </head>
#   <body style="font-family: Arial, sans-serif; line-height: 1.5; direction: rtl;">
#     <h2>{title}</h2>
#     {html_body}
#     <hr/>
#     <div style="font-size:12px; color:#666;">
#       Generated by stocks-alerts
#     </div>
#   </body>
# </html>
# """


# def build_email(
#     ticker: str,
#     interval: str,
#     signal: str,
#     close: float,
#     *,
#     tv_payload: Dict[str, Any] | None = None,
# ) -> Tuple[str, str]:
#     """
#     בונה את נושא המייל ואת גוף המייל (HTML).
#     אוסף נתונים טכניים, פונדמנטליים, חדשות ו-AI.
#     """
#     tv_payload = tv_payload or {}

#     # ========= 1) Price data (Daily MVP) =========
#     # הורדת נתונים מ-Yahoo Finance
#     df = yf.download(ticker, period="1y", interval="1d", auto_adjust=False, progress=False)

#     if df.empty:
#         # טיפול במקרה שבו הטיקר לא נמצא
#         print(f"[BUILD EMAIL] Warning: Empty data for ticker {ticker}")
#         return f"Error: No data for {ticker}", f"<p>Could not fetch data for <b>{ticker}</b>.</p>"

#     # טיפול ב-MultiIndex של yfinance (גרסאות חדשות)
#     if hasattr(df.columns, "levels"):
#         df.columns = [c[0] if isinstance(c, tuple) else c for c in df.columns]

#     df = df.rename(columns={
#         "Open": "open",
#         "High": "high",
#         "Low": "low",
#         "Close": "close",
#         "Volume": "volume",
#     })
#     # סינון עמודות והסרת שורות ריקות
#     df = df[["open", "high", "low", "close", "volume"]].dropna()

#     # ========= 2) Technical =========
#     tech = confluence_score(df)
#     plan = trade_plan(df, tech, rr_min=2.0)
#     chk = checklist_technical(df, tech)

#     # ========= 3) Fundamentals + AI =========
#     fundamentals = {"checks": {}, "metrics": {}, "ai_input": ""}
#     try:
#         fundamentals = fetch_fundamentals_us(ticker)
#     except Exception as e:
#         print(f"[BUILD EMAIL] Fundamentals error: {e}")
#         fundamentals = {"checks": {}, "metrics": {}, "ai_input": ""}

#     checks = fundamentals.get("checks", {}) or {}
#     metrics = fundamentals.get("metrics", {}) or {}

#     ai_fund = ""
#     try:
#         if fundamentals.get("ai_input"):
#             ai_fund = summarize_fundamentals_he(fundamentals["ai_input"])
#     except Exception as e:
#         print(f"[BUILD EMAIL] AI Fund error: {e}")
#         ai_fund = ""

#     # ========= 4) News + AI =========
#     news: List[Dict[str, Any]] = []
#     try:
#         news = get_company_news(ticker, limit=6)
#     except Exception as e:
#         print(f"[BUILD EMAIL] News fetch error: {e}")
#         news = []

#     ai_news = ""
#     try:
#         # מפעיל AI רק אם יש חדשות או שהבקשה מ-TV מכילה מידע רלוונטי
#         ai_news = summarize_news_he(
#             ticker=ticker,
#             signal=signal,
#             tv_payload=tv_payload,
#             news=news,
#         )
#     except Exception as e:
#         print(f"[BUILD EMAIL] AI News error: {e}")
#         ai_news = ""

#     # ========= Helpers =========
#     def esc(x) -> str:
#         """Escape HTML characters"""
#         if x is None:
#             return ""
#         return str(x).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

#     def pct(x):
#         """Format percentage"""
#         if x is None:
#             return "—"
#         try:
#             return f"{float(x):.2f}%"
#         except Exception:
#             return esc(x)

#     # ========= Subject =========
#     subject = f"📈 התראת סווינג | {ticker} | {signal} | ציון {tech.get('score', 0)}/4"

#     # Confluence reasons
#     reasons = tech.get("reasons") or []
#     tech_reasons_html = "".join(f"<li>{esc(r)}</li>" for r in reasons) or "<li>—</li>"

#     # Trade plan HTML
#     if plan.get("ok"):
#         plan_html = f"""
#         <table style="width:100%; border-collapse: collapse;">
#           <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">אזור כניסה</td><td style="border:1px solid #eee;padding:8px">{esc(plan["entry_zone"]["low"])} – {esc(plan["entry_zone"]["high"])}</td></tr>
#           <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">סטופ לוס</td><td style="border:1px solid #eee;padding:8px"><b>{esc(plan["stop_loss"])}</b></td></tr>
#           <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">יעד 1</td><td style="border:1px solid #eee;padding:8px">{esc(plan["tp1"])} (RR {esc(plan["rr1"])})</td></tr>
#           <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">יעד 2</td><td style="border:1px solid #eee;padding:8px">{esc(plan["tp2"])} (RR {esc(plan["rr2"])})</td></tr>
#         </table>
#         """
#     else:
#         plan_html = f"<div style='padding:10px;background:#fff6f6;border:1px solid #ffd2d2;border-radius:10px'>לא נוצרה תוכנית עסקה: {esc(plan.get('reason','—'))}</div>"

#     # Fundamentals HTML
#     if checks:
#         checks_rows = "".join(
#             f"<tr><td style='border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700'>{esc(k)}</td><td style='border:1px solid #eee;padding:8px'>{esc(v)}</td></tr>"
#             for k, v in checks.items()
#         )
#         fundamentals_html = f"""
#         <table style="width:100%; border-collapse: collapse;">
#           {checks_rows}
#         </table>
#         <div style="margin-top:8px;font-size:12px;color:#444">
#           P/E: {esc(metrics.get("pe"))} ·
#           Revenue CAGR: {pct((metrics.get("rev_cagr") or 0) * 100 if metrics.get("rev_cagr") is not None else None)} ·
#           Net Income CAGR: {pct((metrics.get("ni_cagr") or 0) * 100 if metrics.get("ni_cagr") is not None else None)} ·
#           FCF CAGR: {pct((metrics.get("fcf_cagr") or 0) * 100 if metrics.get("fcf_cagr") is not None else None)}
#         </div>
#         """
#     else:
#         fundamentals_html = "<div style='padding:10px;background:#fff6f6;border:1px solid #ffd2d2;border-radius:10px'>לא הצלחתי למשוך נתונים פונדמנטליים כרגע.</div>"

#     # News List HTML
#     if news:
#         news_items = "".join(
#             f"<li><b>{esc(n.get('source',''))}</b> — {esc(n.get('title',''))} "
#             f"<span style='color:#666;font-size:12px'>({esc(n.get('published_at',''))})</span> "
#             f"— <a href='{esc(n.get('url',''))}'>קישור</a></li>"
#             for n in news
#         )
#     else:
#         news_items = "<li>לא נמצאו חדשות משמעותיות כרגע.</li>"

#     # AI Blocks
#     ai_fund_block = ""
#     if ai_fund.strip():
#         ai_fund_block = f"<div style='background:#f6f6f6;border:1px solid #eee;border-radius:10px;padding:10px;white-space:pre-wrap'>{esc(ai_fund)}</div>"

#     ai_news_block = ""
#     if ai_news.strip():
#         ai_news_block = f"<div style='background:#f6f6f6;border:1px solid #eee;border-radius:10px;padding:10px;white-space:pre-wrap'>{esc(ai_news)}</div>"

#     # ========= Final body Construction =========
#     body = f"""
#     <div style="background:#f5f7fb;padding:12px;border-radius:12px">
#       <div style="background:#fff;padding:12px;border-radius:12px;border:1px solid #e6e8ef">
#         <div style="font-size:18px;font-weight:800">📊 התראת סווינג – {esc(ticker)}</div>
#         <div style="color:#555;font-size:13px;margin-top:6px">
#           <b>טיימפריים:</b> {esc(interval)} · <b>סיגנל:</b> {esc(signal)} · <b>מחיר:</b> {esc(close)} ·
#           <b>UTC:</b> {esc(datetime.utcnow().isoformat(timespec="seconds"))}
#         </div>
#       </div>

#       <div style="background:#fff;padding:12px;border-radius:12px;border:1px solid #e6e8ef;margin-top:10px">
#         <div style="font-weight:800;margin-bottom:6px">🧠 Confluence</div>
#         <div><b>ציון:</b> {esc(tech.get("score"))}/4</div>
#         <ul>{tech_reasons_html}</ul>
#       </div>

#       <div style="background:#fff;padding:12px;border-radius:12px;border:1px solid #e6e8ef;margin-top:10px">
#         <div style="font-weight:800;margin-bottom:6px">🎯 Trade Plan (1% risk)</div>
#         {plan_html}
#       </div>

#       <div style="background:#fff;padding:12px;border-radius:12px;border:1px solid #e6e8ef;margin-top:10px">
#         <div style="font-weight:800;margin-bottom:6px">✅ צ’ק־ליסט</div>
#         <table style="width:100%; border-collapse: collapse;">
#           <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">נר אחרון</td><td style="border:1px solid #eee;padding:8px">{esc(chk.get("candle"))}</td></tr>
#           <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">מגמה שבועית</td><td style="border:1px solid #eee;padding:8px">{esc(chk.get("trend_week_pct"))}%</td></tr>
#           <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">מגמה חודשית</td><td style="border:1px solid #eee;padding:8px">{esc(chk.get("trend_month_pct"))}%</td></tr>
#           <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">ווליום</td><td style="border:1px solid #eee;padding:8px">{esc(chk.get("volume"))}</td></tr>
#           <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">MA20</td><td style="border:1px solid #eee;padding:8px">{esc(chk.get("ma20"))}</td></tr>
#           <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">מצב כללי</td><td style="border:1px solid #eee;padding:8px">{esc(chk.get("bull_bear"))}</td></tr>
#         </table>
#       </div>

#       <div style="background:#fff;padding:12px;border-radius:12px;border:1px solid #e6e8ef;margin-top:10px">
#         <div style="font-weight:800;margin-bottom:6px">📘 פונדמנטלי (ארה״ב)</div>
#         {fundamentals_html}
#         <div style="margin-top:10px">
#           <div style="font-weight:800;margin-bottom:6px">🤖 סיכום פונדמנטלי (AI)</div>
#           {ai_fund_block or "<div style='color:#666'>—</div>"}
#         </div>
#       </div>

#       <div style="background:#fff;padding:12px;border-radius:12px;border:1px solid #e6e8ef;margin-top:10px">
#         <div style="font-weight:800;margin-bottom:6px">📰 חדשות אחרונות (Finnhub/RSS)</div>
#         <ul>{news_items}</ul>
#         <div style="margin-top:10px">
#           <div style="font-weight:800;margin-bottom:6px">🧠 למה עכשיו? (News + AI)</div>
#           {ai_news_block or "<div style='color:#666'>—</div>"}
#         </div>
#       </div>

#       <div style="margin-top:12px;color:#777;font-size:12px">
#         ⚠️ למידע לימודי בלבד, לא ייעוץ השקעות.
#       </div>
#     </div>
#     """

#     return subject, build_email_html(subject, body)





# def send_email(subject: str, html: str):
#     print(f"[EMAIL] Preparing to send: {subject}")

#     msg = MIMEMultipart("alternative")
#     msg["Subject"] = subject
#     msg["From"] = SMTP_USER
#     msg["To"] = ALERT_TO_EMAIL
#     msg.attach(MIMEText(html, "html", "utf-8"))

#     host = "smtp.gmail.com"
#     # ננסה 587, אם ימשיך ה-timeout, שווה לנסות לשנות ב-Render ל-25 (לפעמים עובד טוב יותר בענן)
#     port = int(os.getenv("SMTP_PORT", "587"))

#     try:
#         # פתרון ה-IPv4 שכבר עבד לנו (עברנו את unreachable)
#         remote_host = socket.getaddrinfo(host, port, socket.AF_INET)[0][4][0]
#         print(f"[EMAIL] Connecting to {remote_host}:{port}...")

#         # הגדלת ה-timeout ל-30 שניות למקרה של רשת איטית ב-Render
#         server = smtplib.SMTP(remote_host, port, timeout=30)

#         # debuglevel יראה לנו בתוך הלוגים של Render את השיחה המלאה עם גוגל
#         server.set_debuglevel(1)

#         server.ehlo()
#         if server.has_ext("STARTTLS"):
#             print("[EMAIL] Starting TLS...")
#             server.starttls()
#             server.ehlo()

#         print("[EMAIL] Logging in...")
#         server.login(SMTP_USER, SMTP_PASS)

#         server.send_message(msg)
#         server.quit()
#         print(f"[EMAIL] SUCCESS ✅ Sent to {ALERT_TO_EMAIL}")

#     except socket.timeout:
#         print(f"[EMAIL] ERROR ❌: Connection timed out after 30 seconds.")
#     except Exception as e:
#         print(f"[EMAIL] ACTUAL ERROR ❌: {type(e).__name__}: {e}")

# def send_email(subject: str, html: str):
#     print(f"[EMAIL] send_email called. subject={subject!r}")

#     msg = MIMEMultipart("alternative")
#     msg["Subject"] = subject
#     msg["From"] = SMTP_USER
#     msg["To"] = ALERT_TO_EMAIL
#     msg.attach(MIMEText(html, "html", "utf-8"))

#     # שינוי הפורט ל-587 במידה ו-465 חסום
#     port = int(os.getenv("SMTP_PORT", "587"))
#     host = os.getenv("SMTP_HOST", "smtp.gmail.com")

#     try:
#         # שימוש ב-SMTP רגיל + starttls במקום SMTP_SSL
#         with smtplib.SMTP(host, port) as server:
#             server.set_debuglevel(1) # מאפשר לראות לוגים מפורטים של התקשורת
#             server.starttls() # אבטחת החיבור
#             server.login(SMTP_USER, SMTP_PASS)
#             server.send_message(msg)
#         print("[EMAIL] sent ✅")
#     except Exception as e:
#         print(f"[EMAIL] FAILED ❌ {type(e).__name__}: {e}")
#         raise


# def send_email(subject: str, html: str):
#     """שולח את המייל בפועל באמצעות SMTP"""
#     print(f"[EMAIL] send_email called. subject={subject!r}")

#     msg = MIMEMultipart("alternative")
#     msg["Subject"] = subject
#     msg["From"] = SMTP_USER
#     msg["To"] = ALERT_TO_EMAIL

#     msg.attach(MIMEText(html, "html", "utf-8"))

#     print(f"[EMAIL] Connecting to SMTP={SMTP_HOST}:{SMTP_PORT} USER={SMTP_USER} TO={ALERT_TO_EMAIL}")

#     try:
#         with smtplib.SMTP_SSL(SMTP_HOST, SMTP_PORT) as smtp:
#             smtp.login(SMTP_USER, SMTP_PASS)
#             smtp.send_message(msg)
#         print("[EMAIL] sent ✅")
#     except Exception as e:
#         print(f"[EMAIL] FAILED ❌ {type(e).__name__}: {e}")
#         raise




# # app/services/emailer.py
# from __future__ import annotations

# import os
# import smtplib
# from datetime import datetime
# from typing import Any, Dict, List, Tuple

# from email.mime.multipart import MIMEMultipart
# from email.mime.text import MIMEText

# import yfinance as yf

# # SendGrid (HTTP API) — מומלץ ל-Render
# from sendgrid import SendGridAPIClient
# from sendgrid.helpers.mail import Mail

# # הפרויקט שלך
# from app.ta.ta_engine import confluence_score, trade_plan, checklist_technical
# from app.ta.fundamentals_us import fetch_fundamentals_us
# from app.services.ai_summarizer import summarize_fundamentals_he
# from app.services.news_provider import get_company_news
# from app.services.ai_news_summarizer import summarize_news_he


# # ======================================================
# # ENV
# # ======================================================
# SMTP_HOST = os.getenv("SMTP_HOST", "smtp.gmail.com")
# SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
# SMTP_USER = os.getenv("SMTP_USER", "")
# SMTP_PASS = os.getenv("SMTP_PASS", "")

# ALERT_TO_EMAIL = os.getenv("ALERT_TO_EMAIL", "")

# EMAIL_PROVIDER = os.getenv("EMAIL_PROVIDER", "sendgrid").lower().strip()
# SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY", "")

# FROM_EMAIL = os.getenv("FROM_EMAIL", SMTP_USER)  # ב-SendGrid חייב להיות מאומת
# FROM_NAME = os.getenv("FROM_NAME", "stocks-alerts")


# # ======================================================
# # HTML wrapper
# # ======================================================
# def build_email_html(title: str, html_body: str) -> str:
#     return f"""\
# <!doctype html>
# <html>
#   <head>
#     <meta charset="utf-8" />
#     <title>{title}</title>
#   </head>
#   <body style="font-family: Arial, sans-serif; line-height: 1.5; direction: rtl;">
#     <h2>{title}</h2>
#     {html_body}
#     <hr/>
#     <div style="font-size:12px; color:#666;">
#       Generated by stocks-alerts
#     </div>
#   </body>
# </html>
# """


# # ======================================================
# # Build email (HTML)
# # ======================================================
# def build_email(
#     ticker: str,
#     interval: str,
#     signal: str,
#     close: float,
#     *,
#     tv_payload: Dict[str, Any] | None = None,
# ) -> Tuple[str, str]:
#     tv_payload = tv_payload or {}

#     # ========= 1) Price data =========
#     df = yf.download(ticker, period="1y", interval="1d", auto_adjust=False, progress=False)
#     if df.empty:
#         subject = f"❌ שגיאה | אין נתונים ל-{ticker}"
#         body = f"<p>לא הצלחתי למשוך נתונים עבור <b>{ticker}</b> מ-Yahoo Finance.</p>"
#         return subject, build_email_html(subject, body)

#     # normalize yfinance columns
#     if hasattr(df.columns, "levels"):
#         df.columns = [c[0] if isinstance(c, tuple) else c for c in df.columns]

#     df = df.rename(
#         columns={"Open": "open", "High": "high", "Low": "low", "Close": "close", "Volume": "volume"}
#     )
#     df = df[["open", "high", "low", "close", "volume"]].dropna()

#     # ========= 2) Technical =========
#     tech = confluence_score(df)
#     plan = trade_plan(df, tech, rr_min=2.0)
#     chk = checklist_technical(df, tech)

#     # ========= 3) Fundamentals + AI =========
#     fundamentals = {"checks": {}, "metrics": {}, "ai_input": ""}
#     try:
#         fundamentals = fetch_fundamentals_us(ticker)
#     except Exception as e:
#         print(f"[BUILD EMAIL] Fundamentals error: {e}")

#     checks = fundamentals.get("checks", {}) or {}
#     metrics = fundamentals.get("metrics", {}) or {}

#     ai_fund = ""
#     try:
#         ai_input = (fundamentals.get("ai_input") or "").strip()
#         if ai_input:
#             ai_fund = summarize_fundamentals_he(ai_input)
#     except Exception as e:
#         print(f"[BUILD EMAIL] AI Fund error: {e}")
#         ai_fund = ""

#     # ========= 4) News + AI =========
#     news: List[Dict[str, Any]] = []
#     try:
#         news = get_company_news(ticker, limit=6)
#     except Exception as e:
#         print(f"[BUILD EMAIL] News fetch error: {e}")
#         news = []

#     ai_news = ""
#     try:
#         ai_news = summarize_news_he(
#             ticker=ticker,
#             signal=signal,
#             tv_payload=tv_payload,
#             news=news,
#         )
#     except Exception as e:
#         print(f"[BUILD EMAIL] AI News error: {e}")
#         ai_news = ""

#     # ========= Helpers =========
#     def esc(x) -> str:
#         if x is None:
#             return ""
#         return str(x).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

#     def pct(x):
#         if x is None:
#             return "—"
#         try:
#             return f"{float(x):.2f}%"
#         except Exception:
#             return esc(x)

#     # ========= Subject =========
#     subject = f"📈 התראת סווינג | {ticker} | {signal} | ציון {tech.get('score', 0)}/4"

#     # Confluence reasons
#     reasons = tech.get("reasons") or []
#     tech_reasons_html = "".join(f"<li>{esc(r)}</li>" for r in reasons) or "<li>—</li>"

#     # Trade plan block
#     if plan.get("ok"):
#         plan_html = f"""
#         <table style="width:100%; border-collapse: collapse;">
#           <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">אזור כניסה</td><td style="border:1px solid #eee;padding:8px">{esc(plan["entry_zone"]["low"])} – {esc(plan["entry_zone"]["high"])}</td></tr>
#           <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">סטופ לוס</td><td style="border:1px solid #eee;padding:8px"><b>{esc(plan["stop_loss"])}</b></td></tr>
#           <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">יעד 1</td><td style="border:1px solid #eee;padding:8px">{esc(plan["tp1"])} (RR {esc(plan["rr1"])})</td></tr>
#           <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">יעד 2</td><td style="border:1px solid #eee;padding:8px">{esc(plan["tp2"])} (RR {esc(plan["rr2"])})</td></tr>
#         </table>
#         """
#     else:
#         plan_html = f"""
#         <div style='padding:10px;background:#fff6f6;border:1px solid #ffd2d2;border-radius:10px'>
#           לא נוצרה תוכנית עסקה: {esc(plan.get('reason','—'))}
#         </div>
#         """

#     # Fundamentals HTML
#     if checks:
#         checks_rows = "".join(
#             f"<tr><td style='border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700'>{esc(k)}</td>"
#             f"<td style='border:1px solid #eee;padding:8px'>{esc(v)}</td></tr>"
#             for k, v in checks.items()
#         )
#         fundamentals_html = f"""
#         <table style="width:100%; border-collapse: collapse;">{checks_rows}</table>
#         <div style="margin-top:8px;font-size:12px;color:#444">
#           P/E: {esc(metrics.get("pe"))} ·
#           Revenue CAGR: {pct((metrics.get("rev_cagr") or 0) * 100 if metrics.get("rev_cagr") is not None else None)} ·
#           Net Income CAGR: {pct((metrics.get("ni_cagr") or 0) * 100 if metrics.get("ni_cagr") is not None else None)} ·
#           FCF CAGR: {pct((metrics.get("fcf_cagr") or 0) * 100 if metrics.get("fcf_cagr") is not None else None)}
#         </div>
#         """
#     else:
#         fundamentals_html = """
#         <div style='padding:10px;background:#fff6f6;border:1px solid #ffd2d2;border-radius:10px'>
#           לא הצלחתי למשוך נתונים פונדמנטליים כרגע.
#         </div>
#         """

#     # News List HTML (תומך גם במבנה שלך וגם ב-Finnhub)
#     if news:
#         def _headline(n: Dict[str, Any]) -> str:
#             return n.get("headline") or n.get("title") or ""

#         def _published(n: Dict[str, Any]) -> str:
#             return n.get("datetime_utc") or n.get("published_at") or ""

#         news_items = "".join(
#             f"<li><b>{esc(n.get('source',''))}</b> — {esc(_headline(n))} "
#             f"<span style='color:#666;font-size:12px'>({esc(_published(n))})</span> "
#             f"— <a href='{esc(n.get('url',''))}'>קישור</a></li>"
#             for n in news
#         )
#     else:
#         news_items = "<li>לא נמצאו חדשות משמעותיות כרגע.</li>"

#     ai_fund_block = (
#         f"<div style='background:#f6f6f6;border:1px solid #eee;border-radius:10px;padding:10px;white-space:pre-wrap'>{esc(ai_fund)}</div>"
#         if ai_fund.strip()
#         else "<div style='color:#666'>—</div>"
#     )

#     ai_news_block = (
#         f"<div style='background:#f6f6f6;border:1px solid #eee;border-radius:10px;padding:10px;white-space:pre-wrap'>{esc(ai_news)}</div>"
#         if ai_news.strip()
#         else "<div style='color:#666'>—</div>"
#     )

#     body = f"""
#     <div style="background:#f5f7fb;padding:12px;border-radius:12px">
#       <div style="background:#fff;padding:12px;border-radius:12px;border:1px solid #e6e8ef">
#         <div style="font-size:18px;font-weight:800">📊 התראת סווינג – {esc(ticker)}</div>
#         <div style="color:#555;font-size:13px;margin-top:6px">
#           <b>טיימפריים:</b> {esc(interval)} · <b>סיגנל:</b> {esc(signal)} · <b>מחיר:</b> {esc(close)} ·
#           <b>UTC:</b> {esc(datetime.utcnow().isoformat(timespec="seconds"))}
#         </div>
#       </div>

#       <div style="background:#fff;padding:12px;border-radius:12px;border:1px solid #e6e8ef;margin-top:10px">
#         <div style="font-weight:800;margin-bottom:6px">🧠 Confluence</div>
#         <div><b>ציון:</b> {esc(tech.get("score"))}/4</div>
#         <ul>{tech_reasons_html}</ul>
#       </div>

#       <div style="background:#fff;padding:12px;border-radius:12px;border:1px solid #e6e8ef;margin-top:10px">
#         <div style="font-weight:800;margin-bottom:6px">🎯 Trade Plan (1% risk)</div>
#         {plan_html}
#       </div>

#       <div style="background:#fff;padding:12px;border-radius:12px;border:1px solid #e6e8ef;margin-top:10px">
#         <div style="font-weight:800;margin-bottom:6px">✅ צ’ק־ליסט</div>
#         <table style="width:100%; border-collapse: collapse;">
#           <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">נר אחרון</td><td style="border:1px solid #eee;padding:8px">{esc(chk.get("candle"))}</td></tr>
#           <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">מגמה שבועית</td><td style="border:1px solid #eee;padding:8px">{esc(chk.get("trend_week_pct"))}%</td></tr>
#           <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">מגמה חודשית</td><td style="border:1px solid #eee;padding:8px">{esc(chk.get("trend_month_pct"))}%</td></tr>
#           <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">ווליום</td><td style="border:1px solid #eee;padding:8px">{esc(chk.get("volume"))}</td></tr>
#           <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">MA20</td><td style="border:1px solid #eee;padding:8px">{esc(chk.get("ma20"))}</td></tr>
#           <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">מצב כללי</td><td style="border:1px solid #eee;padding:8px">{esc(chk.get("bull_bear"))}</td></tr>
#         </table>
#       </div>

#       <div style="background:#fff;padding:12px;border-radius:12px;border:1px solid #e6e8ef;margin-top:10px">
#         <div style="font-weight:800;margin-bottom:6px">📘 פונדמנטלי (ארה״ב)</div>
#         {fundamentals_html}
#         <div style="margin-top:10px">
#           <div style="font-weight:800;margin-bottom:6px">🤖 סיכום פונדמנטלי (AI)</div>
#           {ai_fund_block}
#         </div>
#       </div>

#       <div style="background:#fff;padding:12px;border-radius:12px;border:1px solid #e6e8ef;margin-top:10px">
#         <div style="font-weight:800;margin-bottom:6px">📰 חדשות אחרונות</div>
#         <ul>{news_items}</ul>
#         <div style="margin-top:10px">
#           <div style="font-weight:800;margin-bottom:6px">🧠 למה עכשיו? (News + AI)</div>
#           {ai_news_block}
#         </div>
#       </div>

#       <div style="margin-top:12px;color:#777;font-size:12px">
#         ⚠️ למידע לימודי בלבד, לא ייעוץ השקעות.
#       </div>
#     </div>
#     """

#     return subject, build_email_html(subject, body)


# # ======================================================
# # Send email (SendGrid default; SMTP optional)
# # ======================================================
# def send_email(subject: str, html: str) -> None:
#     """
#     ב-Render: מומלץ EMAIL_PROVIDER=sendgrid (SMTP חסום בהרבה מקרים)
#     בלוקאלי: אפשר EMAIL_PROVIDER=smtp
#     """
#     if not ALERT_TO_EMAIL:
#         raise RuntimeError("ALERT_TO_EMAIL is missing in env")

#     print(f"[EMAIL] provider={EMAIL_PROVIDER} subject={subject!r} to={ALERT_TO_EMAIL}")

#     # -------- SendGrid (recommended) --------
#     if EMAIL_PROVIDER == "sendgrid":
#         if not SENDGRID_API_KEY:
#             raise RuntimeError("SENDGRID_API_KEY is missing in env")
#         if not FROM_EMAIL:
#             raise RuntimeError("FROM_EMAIL is missing (must be verified in SendGrid)")

#         message = Mail(
#             from_email=(FROM_EMAIL, FROM_NAME),
#             to_emails=ALERT_TO_EMAIL,
#             subject=subject,
#             html_content=html,
#         )
#         try:
#             sg = SendGridAPIClient(SENDGRID_API_KEY)
#             resp = sg.send(message)
#             print(f"[EMAIL] SendGrid OK status={resp.status_code}")
#             return
#         except Exception as e:
#             print(f"[EMAIL] SendGrid FAILED: {e}")
#             raise

#     # -------- SMTP fallback (local) --------
#     if not SMTP_USER or not SMTP_PASS:
#         raise RuntimeError("SMTP_USER/SMTP_PASS missing for SMTP provider")

#     msg = MIMEMultipart("alternative")
#     msg["Subject"] = subject
#     msg["From"] = SMTP_USER
#     msg["To"] = ALERT_TO_EMAIL
#     msg.attach(MIMEText(html, "html", "utf-8"))

#     try:
#         with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=30) as server:
#             server.ehlo()
#             if server.has_extn("STARTTLS"):
#                 server.starttls()
#                 server.ehlo()
#             server.login(SMTP_USER, SMTP_PASS)
#             server.send_message(msg)
#         print("[EMAIL] SMTP OK ✅")
#     except Exception as e:
#         print(f"[EMAIL] SMTP FAILED: {type(e).__name__}: {e}")
#         raise






# app/services/emailer.py
from __future__ import annotations

import os
import smtplib
from datetime import datetime
from typing import Any, Dict, List, Tuple

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import yfinance as yf

# SendGrid (HTTP API) — מומלץ ל-Render
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

# הפרויקט שלך
from app.ta.ta_engine import confluence_score, trade_plan, checklist_technical
from app.ta.fundamentals_us import fetch_fundamentals_us
from app.services.ai_summarizer import summarize_fundamentals_he
from app.services.news_provider import get_company_news
from app.services.ai_news_summarizer import summarize_news_he
from dotenv import load_dotenv
load_dotenv()


# ======================================================
# ENV
# ======================================================
SMTP_HOST = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER = os.getenv("SMTP_USER", "")
SMTP_PASS = os.getenv("SMTP_PASS", "")

ALERT_TO_EMAIL = os.getenv("ALERT_TO_EMAIL", "")

EMAIL_PROVIDER = os.getenv("EMAIL_PROVIDER", "sendgrid").lower().strip()
SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY", "")

FROM_EMAIL = os.getenv("FROM_EMAIL", SMTP_USER)  # ב-SendGrid חייב להיות מאומת
FROM_NAME = os.getenv("FROM_NAME", "stocks-alerts")


# ======================================================
# HTML wrapper
# ======================================================
def build_email_html(title: str, html_body: str) -> str:
    return f"""\
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>{title}</title>
  </head>
  <body style="font-family: Arial, sans-serif; line-height: 1.5; direction: rtl;">
    <h2>{title}</h2>
    {html_body}
    <hr/>
    <div style="font-size:12px; color:#666;">
      Generated by stocks-alerts
    </div>
  </body>
</html>
"""


# ======================================================
# Build email (HTML)
# ======================================================
def build_email(
    ticker: str,
    interval: str,
    signal: str,
    close: float,
    *,
    tv_payload: Dict[str, Any] | None = None,
) -> Tuple[str, str]:
    tv_payload = tv_payload or {}

    # ========= 1) Price data =========
    df = yf.download(ticker, period="1y", interval="1d", auto_adjust=False, progress=False)
    if df.empty:
        subject = f"❌ שגיאה | אין נתונים ל-{ticker}"
        body = f"<p>לא הצלחתי למשוך נתונים עבור <b>{ticker}</b> מ-Yahoo Finance.</p>"
        return subject, build_email_html(subject, body)

    # normalize yfinance columns
    if hasattr(df.columns, "levels"):
        df.columns = [c[0] if isinstance(c, tuple) else c for c in df.columns]

    df = df.rename(
        columns={"Open": "open", "High": "high", "Low": "low", "Close": "close", "Volume": "volume"}
    )
    df = df[["open", "high", "low", "close", "volume"]].dropna()

    # ========= 2) Technical =========
    tech = confluence_score(df)
    plan = trade_plan(df, tech, rr_min=2.0)
    chk = checklist_technical(df, tech)

    # ========= 3) Fundamentals + AI =========
    fundamentals = {"checks": {}, "metrics": {}, "ai_input": ""}
    try:
        fundamentals = fetch_fundamentals_us(ticker)
    except Exception as e:
        print(f"[BUILD EMAIL] Fundamentals error: {e}")

    checks = fundamentals.get("checks", {}) or {}
    metrics = fundamentals.get("metrics", {}) or {}

    ai_fund = ""
    try:
        ai_input = (fundamentals.get("ai_input") or "").strip()
        if ai_input:
            ai_fund = summarize_fundamentals_he(ai_input)
    except Exception as e:
        print(f"[BUILD EMAIL] AI Fund error: {e}")
        ai_fund = ""

    # ========= 4) News + AI =========
    news: List[Dict[str, Any]] = []
    try:
        news = get_company_news(ticker, limit=6)
    except Exception as e:
        print(f"[BUILD EMAIL] News fetch error: {e}")
        news = []

    ai_news = ""
    try:
        ai_news = summarize_news_he(
            ticker=ticker,
            signal=signal,
            news=news,
        )
    except Exception as e:
        print(f"[BUILD EMAIL] AI News error: {e}")
        ai_news = ""

    # ========= Helpers =========
    def esc(x) -> str:
        if x is None:
            return ""
        return str(x).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

    def pct(x):
        if x is None:
            return "—"
        try:
            return f"{float(x):.2f}%"
        except Exception:
            return esc(x)

    # ========= Subject =========
    subject = f"📈 התראת סווינג | {ticker} | {signal} | ציון {tech.get('score', 0)}/4"

    # Confluence reasons
    reasons = tech.get("reasons") or []
    tech_reasons_html = "".join(f"<li>{esc(r)}</li>" for r in reasons) or "<li>—</li>"

    # Trade plan block
    if plan.get("ok"):
        plan_html = f"""
        <table style="width:100%; border-collapse: collapse;">
          <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">אזור כניסה</td><td style="border:1px solid #eee;padding:8px">{esc(plan["entry_zone"]["low"])} – {esc(plan["entry_zone"]["high"])}</td></tr>
          <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">סטופ לוס</td><td style="border:1px solid #eee;padding:8px"><b>{esc(plan["stop_loss"])}</b></td></tr>
          <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">יעד 1</td><td style="border:1px solid #eee;padding:8px">{esc(plan["tp1"])} (RR {esc(plan["rr1"])})</td></tr>
          <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">יעד 2</td><td style="border:1px solid #eee;padding:8px">{esc(plan["tp2"])} (RR {esc(plan["rr2"])})</td></tr>
        </table>
        """
    else:
        plan_html = f"""
        <div style='padding:10px;background:#fff6f6;border:1px solid #ffd2d2;border-radius:10px'>
          לא נוצרה תוכנית עסקה: {esc(plan.get('reason','—'))}
        </div>
        """

    # Fundamentals HTML
    if checks:
        checks_rows = "".join(
            f"<tr><td style='border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700'>{esc(k)}</td>"
            f"<td style='border:1px solid #eee;padding:8px'>{esc(v)}</td></tr>"
            for k, v in checks.items()
        )
        fundamentals_html = f"""
        <table style="width:100%; border-collapse: collapse;">{checks_rows}</table>
        <div style="margin-top:8px;font-size:12px;color:#444">
          P/E: {esc(metrics.get("pe"))} ·
          Revenue CAGR: {pct((metrics.get("rev_cagr") or 0) * 100 if metrics.get("rev_cagr") is not None else None)} ·
          Net Income CAGR: {pct((metrics.get("ni_cagr") or 0) * 100 if metrics.get("ni_cagr") is not None else None)} ·
          FCF CAGR: {pct((metrics.get("fcf_cagr") or 0) * 100 if metrics.get("fcf_cagr") is not None else None)}
        </div>
        """
    else:
        fundamentals_html = """
        <div style='padding:10px;background:#fff6f6;border:1px solid #ffd2d2;border-radius:10px'>
          לא הצלחתי למשוך נתונים פונדמנטליים כרגע.
        </div>
        """

    # News List HTML (תומך גם במבנה שלך וגם ב-Finnhub)
    if news:
        def _headline(n: Dict[str, Any]) -> str:
            return n.get("headline") or n.get("title") or ""

        def _published(n: Dict[str, Any]) -> str:
            return n.get("datetime_utc") or n.get("published_at") or ""

        news_items = "".join(
            f"<li><b>{esc(n.get('source',''))}</b> — {esc(_headline(n))} "
            f"<span style='color:#666;font-size:12px'>({esc(_published(n))})</span> "
            f"— <a href='{esc(n.get('url',''))}'>קישור</a></li>"
            for n in news
        )
    else:
        news_items = "<li>לא נמצאו חדשות משמעותיות כרגע.</li>"

    ai_fund_block = (
        f"<div style='background:#f6f6f6;border:1px solid #eee;border-radius:10px;padding:10px;white-space:pre-wrap'>{esc(ai_fund)}</div>"
        if ai_fund.strip()
        else "<div style='color:#666'>—</div>"
    )

    ai_news_block = (
        f"<div style='background:#f6f6f6;border:1px solid #eee;border-radius:10px;padding:10px;white-space:pre-wrap'>{esc(ai_news)}</div>"
        if ai_news.strip()
        else "<div style='color:#666'>—</div>"
    )

    body = f"""
    <div style="background:#f5f7fb;padding:12px;border-radius:12px">
      <div style="background:#fff;padding:12px;border-radius:12px;border:1px solid #e6e8ef">
        <div style="font-size:18px;font-weight:800">📊 התראת סווינג – {esc(ticker)}</div>
        <div style="color:#555;font-size:13px;margin-top:6px">
          <b>טיימפריים:</b> {esc(interval)} · <b>סיגנל:</b> {esc(signal)} · <b>מחיר:</b> {esc(close)} ·
          <b>UTC:</b> {esc(datetime.utcnow().isoformat(timespec="seconds"))}
        </div>
      </div>

      <div style="background:#fff;padding:12px;border-radius:12px;border:1px solid #e6e8ef;margin-top:10px">
        <div style="font-weight:800;margin-bottom:6px">🧠 Confluence</div>
        <div><b>ציון:</b> {esc(tech.get("score"))}/4</div>
        <ul>{tech_reasons_html}</ul>
      </div>

      <div style="background:#fff;padding:12px;border-radius:12px;border:1px solid #e6e8ef;margin-top:10px">
        <div style="font-weight:800;margin-bottom:6px">🎯 Trade Plan (1% risk)</div>
        {plan_html}
      </div>

      <div style="background:#fff;padding:12px;border-radius:12px;border:1px solid #e6e8ef;margin-top:10px">
        <div style="font-weight:800;margin-bottom:6px">✅ צ’ק־ליסט</div>
        <table style="width:100%; border-collapse: collapse;">
          <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">נר אחרון</td><td style="border:1px solid #eee;padding:8px">{esc(chk.get("candle"))}</td></tr>
          <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">מגמה שבועית</td><td style="border:1px solid #eee;padding:8px">{esc(chk.get("trend_week_pct"))}%</td></tr>
          <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">מגמה חודשית</td><td style="border:1px solid #eee;padding:8px">{esc(chk.get("trend_month_pct"))}%</td></tr>
          <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">ווליום</td><td style="border:1px solid #eee;padding:8px">{esc(chk.get("volume"))}</td></tr>
          <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">MA20</td><td style="border:1px solid #eee;padding:8px">{esc(chk.get("ma20"))}</td></tr>
          <tr><td style="border:1px solid #eee;padding:8px;background:#fafbff;font-weight:700">מצב כללי</td><td style="border:1px solid #eee;padding:8px">{esc(chk.get("bull_bear"))}</td></tr>
        </table>
      </div>

      <div style="background:#fff;padding:12px;border-radius:12px;border:1px solid #e6e8ef;margin-top:10px">
        <div style="font-weight:800;margin-bottom:6px">📘 פונדמנטלי (ארה״ב)</div>
        {fundamentals_html}
        <div style="margin-top:10px">
          <div style="font-weight:800;margin-bottom:6px">🤖 סיכום פונדמנטלי (AI)</div>
          {ai_fund_block}
        </div>
      </div>

      <div style="background:#fff;padding:12px;border-radius:12px;border:1px solid #e6e8ef;margin-top:10px">
        <div style="font-weight:800;margin-bottom:6px">📰 חדשות אחרונות</div>
        <ul>{news_items}</ul>
        <div style="margin-top:10px">
          <div style="font-weight:800;margin-bottom:6px">🧠 למה עכשיו? (News + AI)</div>
          {ai_news_block}
        </div>
      </div>

      <div style="margin-top:12px;color:#777;font-size:12px">
        ⚠️ למידע לימודי בלבד, לא ייעוץ השקעות.
      </div>
    </div>
    """

    return subject, build_email_html(subject, body)


# ======================================================
# Send email (SendGrid default; SMTP optional)
# ======================================================
def send_email(subject: str, html: str) -> None:
    """
    ב-Render: מומלץ EMAIL_PROVIDER=sendgrid (SMTP חסום בהרבה מקרים)
    בלוקאלי: אפשר EMAIL_PROVIDER=smtp
    """
    if not ALERT_TO_EMAIL:
        raise RuntimeError("ALERT_TO_EMAIL is missing in env")

    print(f"[EMAIL] provider={EMAIL_PROVIDER} subject={subject!r} to={ALERT_TO_EMAIL}")

    # -------- SendGrid (recommended) --------
    if EMAIL_PROVIDER == "sendgrid":
        if not SENDGRID_API_KEY:
            raise RuntimeError("SENDGRID_API_KEY is missing in env")
        if not FROM_EMAIL:
            raise RuntimeError("FROM_EMAIL is missing (must be verified in SendGrid)")

        message = Mail(
            from_email=(FROM_EMAIL, FROM_NAME),
            to_emails=ALERT_TO_EMAIL,
            subject=subject,
            html_content=html,
        )
        try:
            sg = SendGridAPIClient(SENDGRID_API_KEY)
            resp = sg.send(message)
            print(f"[EMAIL] SendGrid OK status={resp.status_code}")
            return
        except Exception as e:
            print(f"[EMAIL] SendGrid FAILED: {e}")
            raise

    # -------- SMTP fallback (local) --------
    if not SMTP_USER or not SMTP_PASS:
        raise RuntimeError("SMTP_USER/SMTP_PASS missing for SMTP provider")

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = SMTP_USER
    msg["To"] = ALERT_TO_EMAIL
    msg.attach(MIMEText(html, "html", "utf-8"))

    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=30) as server:
            server.ehlo()
            if server.has_extn("STARTTLS"):
                server.starttls()
                server.ehlo()
            server.login(SMTP_USER, SMTP_PASS)
            server.send_message(msg)
        print("[EMAIL] SMTP OK ✅")
    except Exception as e:
        print(f"[EMAIL] SMTP FAILED: {type(e).__name__}: {e}")
        raise
